### ISSUE TITLE
Скачивание файлов $

### ISSUE THREAD

**Issue by jonotyan** [jonotyan/behealth_bot#1]
15.000
-----------------
Добавление возможности скачивать файлы информационного наполнения

**Comment by Meorwik** [comment]
![Image](https://github.com/jonotyan/behealth_bot/assets/104008026/e2ce188c-6927-4919-8b25-444d95cac8a0)




![Image](https://github.com/jonotyan/behealth_bot/assets/104008026/a370da36-62b4-429f-abf3-0a4cdcbd8655)
